### ISSUE TITLE
[Ingest] prepare and store data c48 gfs ensemble

### ISSUE THREAD

**Issue by cmgas** [JCSDA-internal/r2d2-ingest#24]
## Ingest description

Data type: forecast
Other metadata: gfs
Members: 0-19
Resolution: c48

## Date range

Start date: 2022-02-14T18:00:00Z
End date: 2022-02-18T18:00:00Z
Step: PT6H

## Source host and directory/bucket

Source host: currently on Orion in the experiments DB with the expid: a69fca

## Target data store type (select one)

- [ ] archive
- [ ] experiments
- [x] gfs ensemble
- [ ] other 
    - Please describe: 

## Data store checklist

Data copied into R2D2 on:

- [x] Orion
- [x] S3 (us-east-1)
- [x] S3 (us-east-2)
- [x] S4

**Comment by ericlingerfelt** [comment]
In progress on Orion finally.

**Comment by ericlingerfelt** [comment]
Error on Orion. The MySQL server is overloaded currently and the process exited with the following. 

```
Traceback (most recent call last):
  File "/work2/noaa/da/eric/jedi/venv/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 565, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: Lock wait timeout exceeded; try restarting transaction

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/work2/noaa/da/eric/jedi/jedi-bundle/r2d2/src/r2d2/util/admin_util.py", line 145, in move_experiment
    R2D2Data.move_by_index(item=item,
  File "/work2/noaa/da/eric/jedi/jedi-bundle/r2d2/src/r2d2/r2d2_data.py", line 255, in move_by_index
    R2D2Data.erase_by_index(item, index, source_data_store.get_property('name'))
  File "/work2/noaa/da/eric/jedi/jedi-bundle/r2d2/src/r2d2/r2d2_data.py", line 313, in erase_by_index
    R2D2Data.erase(**kwargs)
  File "/work2/noaa/da/eric/jedi/jedi-bundle/r2d2/src/r2d2/r2d2_data.py", line 436, in erase
    R2D2DataRegister.unregister_data(item, index, int(target_data_store.get_property('data_store_index')))
  File "/work2/noaa/da/eric/jedi/jedi-bundle/r2d2/src/r2d2/r2d2_data_register.py", line 136, in unregister_data
    Query().delete(query, values)
  File "/work2/noaa/da/eric/jedi/jedi-bundle/r2d2/src/r2d2/mysql/query.py", line 33, in delete
    self._execute(query, values)
  File "/work2/noaa/da/eric/jedi/jedi-bundle/r2d2/src/r2d2/mysql/query.py", line 165, in _execute
    self._cursor.execute(query, values)
  File "/work2/noaa/da/eric/jedi/venv/lib/python3.9/site-packages/mysql/connector/cursor_cext.py", line 279, in execute
    result = self._cnx.cmd_query(
  File "/work2/noaa/da/eric/jedi/venv/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 573, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 1205 (HY000): Lock wait timeout exceeded; try restarting transaction
```

We will be updating the R2D2 MySQL server hardware next week.

**Comment by ericlingerfelt** [comment]
In progress again.

**Comment by ericlingerfelt** [comment]
Done on Orion.

**Comment by ericlingerfelt** [comment]
In process on S4 and AWS.

**Comment by ericlingerfelt** [comment]
Done.
