### ISSUE TITLE
[Bug] getBackgroundGEOS fails for skylab-trace-gas-small experiment

### ISSUE THREAD

**Issue by mer-a-o** [JCSDA-internal/r2d2-ingest#35]
## Current behavior (describe the bug)

On both Orion and Discover, `getBackgroundGEOS` fails for skylab-trace-gas-small experiment. 
@ericlingerfelt @cmgas , I'm not sure if the data is not available on r2d2 db or if [skylab-trace-gas-small.yam](https://github.com/JCSDA-internal/skylab/blob/develop/experiments/skylab-trace-gas-small.yaml)l needs an update? 
Here is the error:
```
2023-06-22 15:44:29,989 - DEBUG - r2d2.r2d2_data - Calling fetch with the following key/values: {'model': 'geos_cf', 'item': 'forecast', 'experiment': 'bb65c7', 'step': 'PT6H', 'resolution': 'c24', 'date': '2021-08-01T00:00:00Z', 'target_file': '579716.fc.20210801T000000Z.PT6H.bkg.nc', 'file_extension': 'nc', 'file_type': 'bkg', 'member': -9999}
2023-06-22 15:44:30,688 - DEBUG - r2d2.mysql.database_credentials - Using the following MySQL credentials: {'user': 'r2d2', 'password': '4!dgTrR@7i', 'host': 'r2d2.jcsda.org', 'database': 'r2d2', 'port': '3306'}
2023-06-22 15:44:31,319 - DEBUG - r2d2.r2d2_index - Calling get_by_name with the following key/values: {'item': 'experiment', 'name': 'bb65c7'}
2023-06-22 15:44:31,590 - DEBUG - r2d2.r2d2_index - Calling get_by_name with the following key/values: {'item': 'file_extension', 'name': 'nc'}
2023-06-22 15:44:31,867 - DEBUG - r2d2.r2d2_index - Calling get_by_name with the following key/values: {'item': 'model', 'name': 'geos_cf'}
Traceback (most recent call last):
  File "/work/noaa/da/maryamao/JEDI/jedi-bundle-develop/tmp/ecflow/579716/an/runGetForecast.py", line 39, in <module>
    R2D2Data.fetch(
  File "/work/noaa/da/maryamao/JEDI/jedi-bundle-develop/r2d2/src/r2d2/r2d2_data.py", line 534, in fetch
    raise err.RecordNotFound(item, query, values)
r2d2.error.RecordNotFound.RecordNotFound:
Record does not exist in MySQL Database.
```

**Comment by ericlingerfelt** [comment]
I'll take a look shortly.

**Comment by cmgas** [comment]
Hi @jeromebarre, I'll look too

**Comment by ericlingerfelt** [comment]
```
(venv) JCSDAeric2-MBP:r2d2 eric2$ python3
Python 3.10.8 (main, Apr 27 2023, 12:28:40) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from r2d2 import R2D2Data
>>> R2D2Data.search(item='forecast', experiment='bb65c7', step='PT6H', resolution='c24', date='2021-08-01T00:00:00Z', file_type='bkg', file_extension='nc', model='geos_cf')
2023-06-22 11:07:59,949 - INFO - r2d2.r2d2_data - There are no R2D2Data items matching the submitted search criteria.
[]
```

**Comment by ericlingerfelt** [comment]
I'll check the MySQL database directly.

**Comment by ericlingerfelt** [comment]
The experiment id `bb65c7` is from 2`023-05-08 14:42:31`. It has no forecast files associated with it.

**Comment by ericlingerfelt** [comment]
```
>>> R2D2Data.search(item='forecast', experiment='oper', step='PT6H', resolution='c24', date='2021-08-01T00:00:00Z', file_type='bkg', file_extension='nc', model='geos_cf')
[{'forecast_index': 1055214, 'model': 'geos_cf', 'experiment': 'oper', 'file_extension': 'nc', 'resolution': 'c24', 'domain': '', 'file_type': 'bkg', 'step': 'PT6H', 'tile': -9999, 'member': -9999, 'date': datetime.datetime(2021, 8, 1, 0, 0), 'create_date': datetime.datetime(2023, 5, 8, 14, 43, 30), 'mod_date': datetime.datetime(2023, 5, 12, 18, 2, 19)}]
>>> R2D2Data.find_by_index(item='forecast', index=1055214)
['r2d2-archive-orion', 'r2d2-archive-cheyenne', 'r2d2-archive-discover', 'r2d2-archive-s4', 'r2d2-archive-aws-us-east-1', 'r2d2-archive-aws-us-east-2']
```

**Comment by mer-a-o** [comment]
Thanks @ericlingerfelt. How can I make the experiment use `oper`?

**Comment by ericlingerfelt** [comment]
HI @mer-a-o, You will have to discuss this with @cmgas or someone else who manages the EWOK code.

**Comment by jeromebarre** [comment]
change this line to oper i think https://github.com/JCSDA-internal/skylab/blob/e41fbcbe175180499571ef2a5fe41599096e30a5/experiments/skylab-trace-gas-small.yaml#L18 this should solve the issue
