### ISSUE TITLE
[Ingest] complete bias coefficients population

### ISSUE THREAD

**Issue by BenjaminRuston** [JCSDA-internal/r2d2-ingest#36]
## Ingest description

will need help to double check this, but appears not all the bias coefficients were archived for GOES-17 ABI

the GOES-16 ABI seems fine and no other sensors have issues

These were part of this past issue: https://github.com/JCSDA-internal/r2d2-ingest/issues/10

Data type (observation):

provider: noaa
experiment: oper
model: gfs

## Date range

Start date:  20220301T00Z

End date: 20220315T00Z

## Source host and directory/bucket

Source host: 

Data store directory path or S3 bucket path (_with wildcards if needed_):

## Target data store type (select one)

- [x] archive
- [ ] experiments
- [ ] gfs ensemble
- [ ] other 
    - Please describe: 

## Data store checklist

Data copied into R2D2 on:

- [ ] Cheyenne
- [ ] Discover
- [ ] Orion
- [ ] S3 (us-east-1)
- [ ] S3 (us-east-2)
- [ ] S4

## Associated pull request in [r2d2/scripts](https://github.com/JCSDA-internal/r2d2/tree/develop/scripts) (if creating new ingestion scripts)

*(This instruction will change once we create the r2d2-ingest repository.)*

**Comment by BenjaminRuston** [comment]
@ericlingerfelt this will be outside of the time period needed for skylab-v5 ,,, and could use help verifying this

**Comment by ericlingerfelt** [comment]
Hold on. I will use R2D2's public API to get us a result.

**Comment by ericlingerfelt** [comment]
```
>>> from r2d2 import R2D2Data
>>> R2D2Data.search(item='bias_correction', observation_type='abi_g17_bt_64km', experiment='oper', provider='noaa', model='gfs')
[{'bias_correction_index': 8545, 'model': 'gfs', 'experiment': 'oper', 'provider': 'noaa', 'observation_type': 'abi_g17_bt_64km', 'file_extension': '', 'file_type': 'obsbias_coefficients', 'date': datetime.datetime(2022, 3, 13, 6, 0), 'create_date': datetime.datetime(2023, 3, 24, 17, 23, 36), 'mod_date': datetime.datetime(2023, 3, 24, 17, 23, 36)}, {'bias_correction_index': 8548, 'model': 'gfs', 'experiment': 'oper', 'provider': 'noaa', 'observation_type': 'abi_g17_bt_64km', 'file_extension': '', 'file_type': 'obsbias_tlapse', 'date': datetime.datetime(2022, 3, 13, 6, 0), 'create_date': datetime.datetime(2023, 3, 24, 17, 23, 50), 'mod_date': datetime.datetime(2023, 3, 24, 17, 23, 50)}, {'bias_correction_index': 8593, 'model': 'gfs', 'experiment': 'oper', 'provider': 'noaa', 'observation_type': 'abi_g17_bt_64km', 'file_extension': '', 'file_type': 'obsbias_coeff_errors', 'date': datetime.datetime(2022, 3, 13, 6, 0), 'create_date': datetime.datetime(2023, 3, 24, 17, 27, 15), 'mod_date': datetime.datetime(2023, 3, 24, 17, 27, 15)},....
```

**Comment by ericlingerfelt** [comment]
```
>>> R2D2Data.search(item='bias_correction', observation_type='abi_g17_bt_64km', experiment='oper', provider='noaa', model='gfs', date='20220301T000000Z')
[{'bias_correction_index': 16246, 'model': 'gfs', 'experiment': 'oper', 'provider': 'noaa', 'observation_type': 'abi_g17_bt_64km', 'file_extension': '', 'file_type': 'obsbias_coeff_errors', 'date': datetime.datetime(2022, 3, 1, 0, 0), 'create_date': datetime.datetime(2023, 3, 25, 3, 24, 26), 'mod_date': datetime.datetime(2023, 3, 25, 3, 24, 26)}, {'bias_correction_index': 16283, 'model': 'gfs', 'experiment': 'oper', 'provider': 'noaa', 'observation_type': 'abi_g17_bt_64km', 'file_extension': '', 'file_type': 'obsbias_tlapse', 'date': datetime.datetime(2022, 3, 1, 0, 0), 'create_date': datetime.datetime(2023, 3, 25, 3, 27, 15), 'mod_date': datetime.datetime(2023, 3, 25, 3, 27, 15)}, {'bias_correction_index': 16314, 'model': 'gfs', 'experiment': 'oper', 'provider': 'noaa', 'observation_type': 'abi_g17_bt_64km', 'file_extension': '', 'file_type': 'obsbias_coefficients', 'date': datetime.datetime(2022, 3, 1, 0, 0), 'create_date': datetime.datetime(2023, 3, 25, 3, 29, 36), 'mod_date': datetime.datetime(2023, 3, 25, 3, 29, 36)}]
```

**Comment by ericlingerfelt** [comment]
Looks they are there to me.

**Comment by BenjaminRuston** [comment]
I'm not sure of exactly when it started not finding them... can you try:
`'date': datetime.datetime(2022, 3, 1, 0, 0)`

**Comment by ericlingerfelt** [comment]
Please use the code I listed above to try out new dates. 
```

>>> R2D2Data.find_by_index(item='bias_correction', index=16246)
['r2d2-archive-orion', 'r2d2-archive-cheyenne', 'r2d2-archive-discover', 'r2d2-archive-s4', 'r2d2-archive-aws-us-east-1', 'r2d2-archive-aws-us-east-2']
```

**Comment by BenjaminRuston** [comment]
just did

so it's working here too

**Comment by BenjaminRuston** [comment]
let me try on S4 where I"m having the trouble,, then will look at the ewok scripting this could be something wrong in how it generates the `Fetch`

**Comment by BenjaminRuston** [comment]
`R2D2Data.search(item='bias_correction', observation_type='abi_g17_bt_64km', experiment='oper', provider='noaa', model='gfs', date='20220302T000000Z')`

yields this:
```
[{'bias_correction_index': 13944, 'model': 'gfs', 'experiment': 'oper', 'provider': 'noaa', 'observation_type': 'abi_g17_bt_64km', 'file_extension': '', 'file_type': 'obsbias_tlapse', 'date': datetime.datetime(2022, 3, 2, 0, 0), 'create_date': datetime.datetime(2023, 3, 25, 0, 20, 33), 'mod_date': datetime.datetime(2023, 3, 25, 0, 20, 33)}, {'bias_correction_index': 13948, 'model': 'gfs', 'experiment': 'oper', 'provider': 'noaa', 'observation_type': 'abi_g17_bt_64km', 'file_extension': '', 'file_type': 'obsbias_coeff_errors', 'date': datetime.datetime(2022, 3, 2, 0, 0), 'create_date': datetime.datetime(2023, 3, 25, 0, 20, 51), 'mod_date': datetime.datetime(2023, 3, 25, 0, 20, 51)}, {'bias_correction_index': 13996, 'model': 'gfs', 'experiment': 'oper', 'provider': 'noaa', 'observation_type': 'abi_g17_bt_64km', 'file_extension': '', 'file_type': 'obsbias_coefficients', 'date': datetime.datetime(2022, 3, 2, 0, 0), 'create_date': datetime.datetime(2023, 3, 25, 0, 24, 35), 'mod_date': datetime.datetime(2023, 3, 25, 0, 24, 35)}]
```

**Comment by ericlingerfelt** [comment]
OK. I advise that you get experience using R2D2's API for exploring the database's contents and the data store locations of data files before creating an issue.

**Comment by BenjaminRuston** [comment]
the error for this task:  `getObservationsabi_g17_bt_64km`

is this:
```
Traceback (most recent call last):
  File "/data/users/rustonb/work/JCSDA/JEDI/tmp/ecflow/e5241e/an/obs/getObservationsRun.py", line 66, in <module>
    R2D2Data.fetch(
  File "/data/users/rustonb/work/JCSDA/JEDI/r2d2/src/r2d2/r2d2_data.py", line 534, in fetch
    raise err.RecordNotFound(item, query, values)
r2d2.error.RecordNotFound.RecordNotFound:
Record does not exist in MySQL Database.
Table Name: bias_correction
Query:
SELECT `bias_correction_index` FROM `bias_correction` WHERE `date` = 2022-03-02 00:00:00 AND `file_type` = obsbias_coefficients AND `experiment_index` = 2028 AND `file_extension_index` = 163 AND `model_index` = 3 AND `observation_type_index` = 1281 AND `provider_index` = 72
+ ERROR
```

**Comment by ericlingerfelt** [comment]
OK. So here is what is going on.

**Comment by ericlingerfelt** [comment]
Someone has modified the EWOK code to use the current experiment id (like `e5241e`) instead of using `oper`. Please see https://github.com/JCSDA-internal/r2d2-ingest/issues/35.

**Comment by ericlingerfelt** [comment]
Thank you for your patience!

**Comment by BenjaminRuston** [comment]
will close this,,, had a feeling like the last *r2d2* issue it was actually an `ewok` issue

**Comment by BenjaminRuston** [comment]
Will open an issue in `ewok` as r2d2 is fine
